### ISSUE TITLE
Bug: Is there a bug in EatAction?

### ISSUE THREAD

**Issue by a38782615** [crashkonijn/GOAP#65] opened 2023-07-06 08:36 UTC
not arrived at the Apple possition and then eat the apple！！！

sorry it is my fault

**Comment by SiliconOrchid** [comment] 2023-07-06 11:14
@a38782615 could you provide more information about how this scenario appeared for you.      E.g. any steps to reproduce.    Screenshot of the bug could be useful way to communicate the problem (e.g. showing a screenshot of the GOAP node viewer at the relevant moment).

**Comment by a38782615** [comment] 2023-07-06 12:02
1:use the ComplexScene 
2:use only one WoodCutter
3:disable the ironMine,Box,Anvil
4:run the scene
5:when the apples appear int the scene and the WoodCutter is hungry ,then the WoodCutter will eat apple but it is't at the apple possition

**Comment by crashkonijn** [comment] 2023-07-10 06:23
Hi @a38782615 thanks for having a go at the project!

Since you edited in that you've found the issue I'm going to close this.

If you do run into issues again don't hesitate to create a ticket again. Please do provide more information next time like @SiliconOrchid suggested, based on the description that you gave we'd be unable to help you :)

**Closed by crashkonijn** 2023-07-10 06:23 UTC
Labels: bug
